Repository CorsixTH/CorsixTH, pull requests merged in 2021-08, with the labels that each got.

#2024 Move staff advice/announcements to player hospital
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/entities/humanoids/staff.lua
  CorsixTH/Lua/entities/humanoids/staff/doctor.lua
  CorsixTH/Lua/entities/humanoids/staff/handyman.lua
  CorsixTH/Lua/entities/humanoids/staff/nurse.lua
  CorsixTH/Lua/entities/humanoids/staff/receptionist.lua
  CorsixTH/Lua/hospital.lua
  CorsixTH/Lua/hospitals/player_hospital.lua
  CorsixTH/Lua/room.lua
Labels: PR:Refactor

#1852 [RDY] Add to reception queue only when near reception #372
  CorsixTH/Lua/humanoid_actions/seek_reception.lua
Labels: PR:Improvement

#1873 Handymen
  CorsixTH/Lua/entities/machine.lua
Labels: PR:Improvement

#1861 [RDY] Correct UIResearch Behaviour on demo[2]
  CorsixTH/Lua/dialogs/bottom_panel.lua
  CorsixTH/Lua/dialogs/fullscreen/research_policy.lua
Labels: PR:Bugfix

#2037 Remove .0 from negatives in Annual Report
  CorsixTH/Lua/dialogs/fullscreen/annual_report.lua
Labels: PR:Bugfix
