Repository CorsixTH/CorsixTH, pull requests merged in 2021-07, with the labels that each got.

#1980 Fix case insensitive file selection in Animview
  AnimView/frmSprites.cpp
Labels: PR:Bugfix

#1969 [RDY] Move advisor check on raise request
  CorsixTH/Lua/entities/humanoids/staff.lua
  CorsixTH/Lua/hospital.lua
  CorsixTH/Lua/hospitals/player_hospital.lua
Labels: PR:Bugfix

#1984 Use scoped class to reset SDL_SetTextureColorMod for glowing effect.
  CorsixTH/Src/th_gfx_sdl.cpp
Labels: PR:Improvement

#1833 Put system information at the start of gamelog.txt
  .github/workflows/Linux.yml
  CMakeLists.txt
  CorsixTH/CMakeLists.txt
  CorsixTH/Lua/api_version.lua
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/world.lua
  CorsixTH/Src/config.h.in
  CorsixTH/Src/th_lua.cpp
Labels: PR:Improvement

#1706 Patients in a ward may stay in bed when the nurse leaves
  .luacheckrc
  CorsixTH/Lua/entities/humanoids/staff.lua
  CorsixTH/Lua/room.lua
  CorsixTH/Lua/rooms/ward.lua
Labels: PR:Feature

#1988 Machine repair changes
  CorsixTH/Lua/entities/machine.lua
  CorsixTH/Lua/hospital.lua
  CorsixTH/Lua/hospitals/player_hospital.lua
Labels: PR:Refactor

#2002 Let dropdowns close when clicked outside of
  CorsixTH/Lua/dialogs/resizables/dropdown.lua
Labels: PR:Improvement

#2009 [RDY] Backport Trophy Fix (0.65)
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/map.lua
  CorsixTH/com.corsixth.corsixth.metainfo.xml
  changelog.txt
Labels: PR:Bugfix

#1942 New layout for hotkey settings
  .luacheckrc
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/dialogs/resizables/hotkey_assign.lua
  CorsixTH/Lua/languages/brazilian_portuguese.lua
  CorsixTH/Lua/languages/english.lua
  CorsixTH/Lua/languages/greek.lua
  CorsixTH/Lua/languages/simplified_chinese.lua
  CorsixTH/Lua/languages/traditional_chinese.lua
  CorsixTH/Lua/window.lua
Labels: PR:Improvement

#2010 [RDY] Apply all cures trophy variables (permfix)
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/map.lua
  CorsixTH/com.corsixth.corsixth.metainfo.xml
  changelog.txt
Labels: PR:Bugfix

#1975 [RDY] Fullscreen Hotkey updates options button
  CorsixTH/Lua/dialogs/resizables/options.lua
  CorsixTH/Lua/ui.lua
Labels: PR:Bugfix

#2026 Announce VIP arrival in local hospital only
  CorsixTH/Lua/entities/humanoids/vip.lua
  CorsixTH/Lua/hospital.lua
  CorsixTH/Lua/hospitals/player_hospital.lua
  CorsixTH/Lua/world.lua
Labels: PR:Refactor

#2015 [RDY] Ask litter for hospital
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/humanoid_actions/sweep_floor.lua
  CorsixTH/Lua/objects/litter.lua
Labels: PR:Bugfix
