Repository CorsixTH/CorsixTH, pull requests merged in 2022-05, with the labels that each got.

#2158 Fix version compare on update
  CorsixTH/Lua/app.lua
Labels: PR:Bugfix

#2125 Refresh dynamic info at load
  CorsixTH/Lua/dialogs/fullscreen/fax.lua
  CorsixTH/Lua/dialogs/patient.lua
  CorsixTH/Lua/dialogs/queue_dialog.lua
  CorsixTH/Lua/entities/humanoids/patient.lua
  CorsixTH/Lua/entities/humanoids/staff.lua
  CorsixTH/Lua/entities/machine.lua
  CorsixTH/Lua/entities/object.lua
  CorsixTH/Lua/humanoid_actions/seek_reception.lua
  CorsixTH/Lua/humanoid_actions/seek_room.lua
  CorsixTH/Lua/humanoid_actions/seek_toilets.lua
  CorsixTH/Lua/objects/door.lua
  CorsixTH/Lua/rooms/gp.lua
Labels: PR:Improvement, PR:Refactor

#2148 Toggle Cheat System Upgrade
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/cheats.lua
  CorsixTH/Lua/dialogs/fullscreen/fax.lua
  CorsixTH/Lua/entities/humanoids/staff.lua
  CorsixTH/Lua/hospital.lua
  CorsixTH/Lua/hospitals/ai_hospital.lua
  CorsixTH/Lua/hospitals/player_hospital.lua
  CorsixTH/Lua/languages/english.lua
  CorsixTH/Lua/world.lua
Labels: PR:Feature, PR:Refactor

#2166 Refactor clipping on render_target to keep a stack of clips.
  CorsixTH/Lua/dialogs/message.lua
  CorsixTH/Src/th_gfx.cpp
  CorsixTH/Src/th_gfx_sdl.cpp
  CorsixTH/Src/th_gfx_sdl.h
  CorsixTH/Src/th_lua_gfx.cpp
  CorsixTH/Src/th_map.cpp
Labels: PR:Refactor

#2172 Reinstate legacy strings for VIP
  CorsixTH/Lua/languages/english.lua
Labels: PR:Bugfix

#2174 Fix advice call in boiler repair
  CorsixTH/Lua/calls_dispatcher.lua
  CorsixTH/Lua/hospital.lua
  CorsixTH/Lua/world.lua
Labels: PR:Bugfix
