Repository CorsixTH/CorsixTH, pull requests merged in 2022-07, with the labels that each got.

#2191 Add cli function for decoding RNC files.
  AnimView/th.cpp
  CMakeLists.txt
  CorsixTH/Src/lua_rnc.cpp
  libs/rnc/CMakeLists.txt
  tools/CMakeLists.txt
  tools/rnc/CMakeLists.txt
  tools/rnc/rnc_decode_cli.cpp
Labels: PR:Feature

#2198 Add Triangular disitrbution function.
  .luacheckrc
  CorsixTH/Lua/app.lua
Labels: PR:Feature

#2208 Obey GP's Diagnosis Room Choice
  CorsixTH/Lua/humanoid_actions/seek_room.lua
Labels: PR:Improvement

#2203 Replace hospitals[1] in code
  CorsixTH/Lua/dialogs/fullscreen/annual_report.lua
  CorsixTH/Lua/world.lua
Labels: PR:Refactor
