Repository CorsixTH/CorsixTH, pull requests merged in 2022-09, with the labels that each got.

#2233 Fix Font Picker's back button
  CorsixTH/Lua/dialogs/resizables/file_browsers/choose_font.lua
Labels: PR:Bugfix

#2234 Ensure handymen wait for patients to leave
  CorsixTH/Lua/entities/machine.lua
Labels: PR:Bugfix

#2249 Fix walls afterLoad 172
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/world.lua
Labels: PR:Bugfix

#2244 [RDY] Save confirm_button state when editing room
  CorsixTH/Lua/dialogs/edit_room.lua
Labels: PR:Bugfix

#2247 Improve debug patient handling
  CorsixTH/Lua/dialogs/patient.lua
  CorsixTH/Lua/dialogs/resizables/menu_list_dialogs/make_debug_patient.lua
  CorsixTH/Lua/languages/english.lua
Labels: PR:Bugfix, PR:Refactor

#2232 Add OK to Filebrowser
  CorsixTH/Lua/dialogs/resizables/file_browser.lua
  CorsixTH/Lua/dialogs/resizables/file_browsers/save_game.lua
  CorsixTH/Lua/dialogs/resizables/file_browsers/save_map.lua
  CorsixTH/Lua/dialogs/tree_ctrl.lua
  CorsixTH/Lua/languages/english.lua
Labels: PR:Feature
