Repository CorsixTH/CorsixTH, pull requests merged in 2022-10, with the labels that each got.

#2236 Refactor improveDrug
  CorsixTH/Lua/research_department.lua
Labels: PR:Improvement, PR:Refactor

#2260 Serious radiation should not be a contagious disease
  CorsixTH/Lua/diseases/serious_radiation.lua
Labels: PR:Bugfix

#2259 PR - Removal of IRC, Mailing List and Forum references. Addition of Discord, Reddit and Matrix references.
  CorsixTH/Lua/languages/english.lua
Labels: PR:Improvement

#2219 Changes to max_salary behaviour
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/base_config.lua
  CorsixTH/Lua/dialogs/fullscreen/staff_management.lua
  CorsixTH/Lua/dialogs/staff_rise.lua
  CorsixTH/Lua/entities/humanoid.lua
  CorsixTH/Lua/entities/humanoids/staff.lua
  CorsixTH/Lua/map.lua
Labels: PR:Improvement

#2237 Realign Traditional Chinese Credit strings
  CorsixTH/Lua/languages/traditional_chinese.lua
Labels: PR:Translation

#2268 Add demo gameplay movie
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/dialogs/resizables/main_menu.lua
  CorsixTH/Lua/movie_player.lua
  README.md
Labels: PR:Feature

#2257 Remove destroyed patients from epidemics
  CorsixTH/Lua/epidemic.lua
Labels: PR:Bugfix

#2265 Handyman and plant Monthly advice checks
  CorsixTH/Lua/hospital.lua
  CorsixTH/Lua/hospitals/player_hospital.lua
Labels: PR:Refactor

#2271 Compress png images
  LDocGen/output/logo.png
  LevelEdit/src/icon128.png
  LevelEdit/src/icon16.png
  LevelEdit/src/icon24.png
  LevelEdit/src/icon256.png
  LevelEdit/src/icon32.png
  LevelEdit/src/icon48.png
  LevelEdit/src/icon64.png
Labels: PR:Improvement

#2270 Refactor use object tilespeed
  CorsixTH/Lua/humanoid_actions/multi_use_object.lua
  CorsixTH/Lua/humanoid_actions/use_object.lua
Labels: PR:Refactor

#2217 Show queueing patients when hovering the door
  CorsixTH/Lua/game_ui.lua
  LICENSE.txt
Labels: PR:Improvement

#2276 Check for updates menu option
  CorsixTH/Lua/dialogs/resizables/main_menu.lua
  CorsixTH/Lua/dialogs/resizables/options.lua
  CorsixTH/Lua/languages/czech.lua
  CorsixTH/Lua/languages/english.lua
Labels: PR:Improvement

#2282 Properly apply Roujin's challenge
  CorsixTH/Lua/world.lua
Labels: PR:Bugfix

#2277 Chinese updates by lokpro
  CorsixTH/Lua/languages/simplified_chinese.lua
  CorsixTH/Lua/languages/traditional_chinese.lua
Labels: PR:Translation
