Repository CorsixTH/CorsixTH, pull requests merged in 2022-04, with the labels that each got.

#2122 Fix hotkey tooltip
  CorsixTH/Lua/dialogs/resizables/hotkey_assign.lua
Labels: PR:Bugfix

#2080 Dynamic Info - Machine replacement strength
  CorsixTH/Levels/original08.level
  CorsixTH/Lua/entities/machine.lua
  CorsixTH/Lua/languages/english.lua
  CorsixTH/Lua/research_department.lua
Labels: PR:Improvement

#2115 Update German translation
  CorsixTH/Lua/languages/german.lua
Labels: PR:Improvement

#2146 Update macos_luarocks
  scripts/macos_luarocks
Labels: PR:Refactor

#2139 Hospitals store their tile object counts.
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/hospital.lua
  CorsixTH/Lua/world.lua
Labels: PR:Refactor

#2136 Local hospital advice 2
  CorsixTH/Lua/entities/humanoids/patient.lua
  CorsixTH/Lua/hospital.lua
  CorsixTH/Lua/languages/english.lua
  CorsixTH/Lua/rooms/gp.lua
  CorsixTH/Lua/rooms/operating_theatre.lua
  CorsixTH/Lua/rooms/pharmacy.lua
  CorsixTH/Lua/rooms/psych.lua
  CorsixTH/Lua/rooms/research.lua
  CorsixTH/Lua/rooms/training.lua
  CorsixTH/Lua/rooms/ward.lua
  CorsixTH/Lua/world.lua
Labels: PR:Refactor

#2138 [RDY] Charts dialog updates on new month and changes scale in correct order
  CorsixTH/Lua/dialogs/fullscreen/graphs.lua
Labels: PR:Improvement

#2140 Prevent epidemic infection outside hospital
  CorsixTH/Lua/epidemic.lua
Labels: PR:Improvement

#2143 Fix knockdoor action in flight.
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/humanoid_action.lua
Labels: PR:Bugfix

#2147 Portable app/whereami fix
  CorsixTH/Src/main.cpp
  libs/whereami/whereami.c
Labels: PR:Bugfix
