Repository CorsixTH/CorsixTH, pull requests merged in 2023-05, with the labels that each got.

#2326 Clean edit_room afterload
  CorsixTH/Lua/dialogs/edit_room.lua
Labels: PR:Bugfix

#2324 Use ffmpeg 5.1 new channel layout api
  CorsixTH/Src/th_movie.cpp
  CorsixTH/Src/th_movie.h
Labels: PR:Refactor, PR:need-rebase

#2315 try to fix infinite loop when word wider than box Width
  CorsixTH/Src/th_gfx_font.cpp
Labels: PR:Bugfix, PR:need-rebase

#2329 Init Campaigns Directory (fixed)
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/config_finder.lua
  WindowsInstaller/config_template.txt
Labels: PR:Feature

#2332 Replace debug.getinfo with App:getFullPath
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/dialogs/resizables/menu_list_dialogs/custom_campaign.lua
  CorsixTH/Lua/graphics.lua
  CorsixTH/Lua/map.lua
  CorsixTH/Lua/strings.lua
  CorsixTH/Lua/ui.lua
Labels: PR:Refactor

#2333 Safeguard staffWaitToggle for entering patients
  CorsixTH/Lua/room.lua
Labels: PR:Bugfix

#2334 Fix dynamic info on wakecheat
  CorsixTH/Lua/entities/humanoids/staff.lua
Labels: PR:Bugfix

#2340 Add option to disable demo movie
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/config_finder.lua
  WindowsInstaller/config_template.txt
Labels: PR:Improvement

#2283 Cleanup seek reception
  CorsixTH/Lua/humanoid_actions/seek_reception.lua
  CorsixTH/Lua/humanoid_actions/spawn.lua
Labels: PR:Refactor, PR:need-rebase

#2343 Bump vcpkg for fluidsynth seek fix
  CMake/VcpkgDeps.cmake
Labels: PR:Improvement
