Repository CorsixTH/CorsixTH, pull requests merged in 2023-06, with the labels that each got.

#2346 repatch 2135/2333
  CorsixTH/Lua/room.lua
  CorsixTH/Lua/world.lua
Labels: PR:Bugfix

#2345 Update russian.lua
  CorsixTH/Lua/languages/russian.lua
Labels: PR:Translation

#2339 Luacheck warnings inlining
  .luacheckrc
  CorsixTH/CorsixTH.lua
  CorsixTH/Lua/dialogs/bottom_panel.lua
  CorsixTH/Lua/dialogs/edit_room.lua
  CorsixTH/Lua/dialogs/fullscreen/bank_manager.lua
  CorsixTH/Lua/dialogs/fullscreen/town_map.lua
  CorsixTH/Lua/dialogs/menu.lua
  CorsixTH/Lua/dialogs/resizables/file_browser.lua
  CorsixTH/Lua/dialogs/resizables/lua_console.lua
  CorsixTH/Lua/dialogs/resizables/menu_list_dialog.lua
  CorsixTH/Lua/dialogs/tree_ctrl.lua
  CorsixTH/Lua/entities/humanoid.lua
  CorsixTH/Lua/entities/humanoids/inspector.lua
  CorsixTH/Lua/entities/humanoids/staff.lua
  CorsixTH/Lua/entities/humanoids/staff/doctor.lua
  CorsixTH/Lua/entities/humanoids/vip.lua
  CorsixTH/Lua/entities/object.lua
  CorsixTH/Lua/entity.lua
  CorsixTH/Lua/epidemic.lua
  CorsixTH/Lua/game_ui.lua
  CorsixTH/Lua/hospital.lua
  CorsixTH/Lua/humanoid_actions/idle.lua
  CorsixTH/Lua/humanoid_actions/multi_use_object.lua
  CorsixTH/Lua/humanoid_actions/pickup.lua
  CorsixTH/Lua/humanoid_actions/seek_room.lua
  CorsixTH/Lua/humanoid_actions/vaccinate.lua
  CorsixTH/Lua/humanoid_actions/vip_go_to_next_room.lua
  CorsixTH/Lua/rooms/staff_room.lua
  CorsixTH/Lua/sprite_viewer.lua
  CorsixTH/Lua/strict.lua
  CorsixTH/Lua/ui.lua
  CorsixTH/Luatest/non_strict.lua
Labels: PR:Refactor

#2350 Remove luacheck warning 582
  CorsixTH/Lua/world.lua
Labels: PR:Refactor

#2349 Fix casebook label for alien dna
  CorsixTH/Lua/staff_profile.lua
Labels: PR:Bugfix
