Repository CorsixTH/CorsixTH, pull requests merged in 2023-11, with the labels that each got.

#2395 FIX Crash seek_reception.lua:47: attempt to perform arithmetic on a boolean value (local 'this_score')
  CorsixTH/Lua/humanoid_actions/seek_reception.lua
Labels: PR:Bugfix

#2441 Patients may only litter indoors
  CorsixTH/Lua/entities/humanoids/patient.lua
Labels: PR:Bugfix

#2449 Refactor World:findRoomNear
  CorsixTH/Lua/world.lua
Labels: PR:Refactor

#2446 Movies in ISOs
  CorsixTH/Lua/api_version.lua
  CorsixTH/Lua/filesystem.lua
  CorsixTH/Lua/movie_player.lua
  CorsixTH/Src/iso_fs.cpp
  CorsixTH/Src/iso_fs.h
  CorsixTH/Src/th_lua_iso.cpp
Labels: PR:Feature

#2435 Add vaccinate sound for epidemics
  CorsixTH/Lua/epidemic.lua
  CorsixTH/Lua/hospital.lua
  CorsixTH/Lua/hospitals/player_hospital.lua
Labels: PR:Improvement

#2458 Update russian.lua
  CorsixTH/Lua/languages/russian.lua
Labels: PR:Translation

#2416 Advice player of new machine cost
  CorsixTH/Lua/dialogs/machine_dialog.lua
  CorsixTH/Lua/languages/english.lua
  CorsixTH/Lua/strings.lua
Labels: PR:Improvement

#2375 button for mouse panning can be toggled to be the middle or the right mouse button
  CorsixTH/Lua/config_finder.lua
  CorsixTH/Lua/dialogs/resizables/options.lua
  CorsixTH/Lua/game_ui.lua
  CorsixTH/Lua/languages/english.lua
  WindowsInstaller/config_template.txt
Labels: PR:Feature
