Repository CorsixTH/CorsixTH, pull requests merged in 2023-10, with the labels that each got.

#2437 Update spanish translations
  CorsixTH/Lua/languages/spanish.lua
Labels: PR:Translation

#2411 The continue button/switch only loads filenames ending with .sav
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/dialogs/resizables/main_menu.lua
Labels: PR:Bugfix

#2420 Move the emergency announcement and advice to the first patient spawn
  CorsixTH/Lua/dialogs/fullscreen/fax.lua
  CorsixTH/Lua/objects/helicopter.lua
Labels: PR:Improvement

#2438 Fix map editor player count menu
  CorsixTH/Lua/dialogs/menu.lua
  CorsixTH/Lua/map.lua
Labels: PR:Improvement
