Repository CorsixTH/CorsixTH, pull requests merged in 2024-07, with the labels that each got.

#2582 Tidy README file
  README.md
Labels: PR:Build/Repo

#2580 Remove legacy VIP strings
  CorsixTH/Lua/languages/dutch.lua
  CorsixTH/Lua/languages/english.lua
  CorsixTH/Lua/languages/french.lua
  CorsixTH/Lua/languages/simplified_chinese.lua
  CorsixTH/Lua/languages/spanish.lua
  CorsixTH/Lua/languages/traditional_chinese.lua
Labels: PR:Translation

#2545 Add confirmation window to map editor restart
  CorsixTH/Lua/dialogs/menu.lua
  CorsixTH/Lua/dialogs/resizables/file_browsers/save_map.lua
  CorsixTH/Lua/game_ui.lua
  CorsixTH/Lua/languages/english.lua
Labels: PR:Improvement

#2586 Include missing Dutch translation keys
  CorsixTH/Lua/languages/dutch.lua
Labels: PR:Translation

#2583 Add map editor hotkeys
  CorsixTH/Lua/dialogs/resizables/map_editor.lua
Labels: PR:Improvement

#2589 Update Cmakelists
  CMakeLists.txt
Labels: PR:Build/Repo

#2573 Refactor earthquakes to its own class
  .luacheckrc
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/cheats.lua
  CorsixTH/Lua/earthquake.lua
  CorsixTH/Lua/hospital.lua
  CorsixTH/Lua/hospitals/player_hospital.lua
  CorsixTH/Lua/world.lua
Labels: PR:Refactor

#2590 French updates
  CorsixTH/Lua/languages/french.lua
  LICENSE.txt
Labels: PR:Translation

#2592 Update LICENSE.txt
  LICENSE.txt
Labels: PR:Build/Repo

#2565 Updating russian strings
  CorsixTH/Lua/languages/russian.lua
Labels: PR:Translation
