Repository CorsixTH/CorsixTH, pull requests merged in 2024-04, with the labels that each got.

#2548 Italian translation update
  CorsixTH/Lua/languages/italian.lua
  LICENSE.txt
Labels: PR:Translation

#2482 Make the tips window adapt to the space beside the main menu
  CorsixTH/Lua/dialogs/resizables/tip_of_the_day.lua
Labels: PR:Improvement

#2555 Fix missing initial in staff names
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/staff_profile.lua
  CorsixTH/Lua/world.lua
Labels: PR:Bugfix

#2550 Support external XMI again
  CorsixTH/Lua/audio.lua
Labels: PR:Bugfix

#2551 Fix check for audio in menus
  CorsixTH/Lua/dialogs/menu.lua
Labels: PR:Bugfix

#2529 Add a function to get humanoid attribute values
  CorsixTH/Lua/calls_dispatcher.lua
  CorsixTH/Lua/cheats.lua
  CorsixTH/Lua/dialogs/fullscreen/staff_management.lua
  CorsixTH/Lua/dialogs/patient.lua
  CorsixTH/Lua/dialogs/staff_dialog.lua
  CorsixTH/Lua/entities/humanoid.lua
  CorsixTH/Lua/entities/humanoids/patient.lua
  CorsixTH/Lua/entities/humanoids/staff.lua
  CorsixTH/Lua/entities/humanoids/staff/doctor.lua
  CorsixTH/Lua/entities/humanoids/staff/handyman.lua
  CorsixTH/Lua/entities/humanoids/vip.lua
  CorsixTH/Lua/humanoid_actions/use_staffroom.lua
  CorsixTH/Lua/rooms/electrolysis.lua
  CorsixTH/Lua/rooms/gp.lua
Labels: PR:Bugfix

#2540 Add an option to use the advance level movie in custom campaigns
  CorsixTH/Campaigns/example.campaign
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/dialogs/fullscreen/fax.lua
Labels: PR:Improvement

#2528 Refactor staff happiness calculation
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/entities/humanoids/staff.lua
  CorsixTH/Lua/room.lua
Labels: PR:Refactor

#2541 Remove queued StaffRise messages on sack/die
  CorsixTH/Lua/entities/humanoids/staff.lua
Labels: PR:Bugfix
