Repository CorsixTH/CorsixTH, pull requests merged in 2024-11, with the labels that each got.

#2703 Make VIP walk slow
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/entities/humanoids/vip.lua
  CorsixTH/Lua/humanoid_actions/walk.lua
Labels: PR:Improvement

#2688 Smooth out gameplay at normal speed
  .gitignore
  CorsixTH/Lua/api_version.lua
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/game_ui.lua
  CorsixTH/Lua/world.lua
  CorsixTH/Src/lua_sdl.h
Labels: PR:Bugfix

#2707 Remove obsolete remote debugger code
  CorsixTH/CorsixTH.lua
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/config_finder.lua
  CorsixTH/Lua/debug_script.lua
  CorsixTH/Lua/dialogs/menu.lua
  CorsixTH/Lua/dialogs/resizables/hotkey_assign.lua
  CorsixTH/Lua/run_debugger.lua
  CorsixTH/Lua/ui.lua
  README.txt
  WindowsInstaller/config_template.txt
Labels: PR:Build/Repo

#2704 Fix end condition check for hospital balance
  CorsixTH/Lua/endconditions.lua
Labels: PR:Bugfix

#2709 Bump vcpkg packages and remove SDL version lock
  .github/workflows/Windows.yml
  vcpkg-configuration.json
  vcpkg.json
Labels: PR:Build/Repo

#2715 Stop mouse capture on initial TH Selection screen
  CorsixTH/Lua/app.lua
Labels: PR:Bugfix

#2717 Shorten French cheat strings
  CorsixTH/Lua/languages/french.lua
Labels: PR:Translation

#2706 Use date and time in log filenames
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/world.lua
Labels: PR:Feature

#2710 Add new language (Japanese)
  .luacheckrc
  CorsixTH/Lua/config_finder.lua
  CorsixTH/Lua/languages/japanese.lua
  LICENSE.txt
  WindowsInstaller/config_template.txt
Labels: PR:Translation

#2605 soda price can now configurable in the level file
  CorsixTH/Levels/example.level
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/base_config.lua
  CorsixTH/Lua/hospital.lua
  CorsixTH/Lua/map.lua
Labels: PR:Feature

#2725 Add new criteria - staff and patient happiness
  CorsixTH/Lua/endconditions.lua
  CorsixTH/Lua/languages/english.lua
Labels: PR:Feature

#2702 Debug patients properly deregister on autopsy
  CorsixTH/Lua/entities/humanoids/patient.lua
  CorsixTH/Lua/hospital.lua
Labels: PR:Bugfix

#2727 Set minimum possible machine strength after repair to 2
  CorsixTH/Lua/entities/machine.lua
Labels: PR:Improvement
