Repository CorsixTH/CorsixTH, pull requests merged in 2024-02, with the labels that each got.

#2479 Fix background music error message
  CorsixTH/Lua/audio.lua
Labels: PR:Bugfix

#2480 Tidy root CorsixTH.lua
  CorsixTH/CorsixTH.lua
Labels: PR:Refactor, PR:Repo

#2474 Patch Lua Bitmap Makefiles
  CorsixTH/Bitmap/example.spec
  CorsixTH/Bitmap/lib_bmp.lua
  CorsixTH/Bitmap/lib_spritesheet.lua
  CorsixTH/Bitmap/mkfont.lua
  CorsixTH/Bitmap/mkraw.lua
  CorsixTH/Bitmap/mksheet.lua
Labels: PR:Repo

#2485 Remove unused original_path string
  CorsixTH/Lua/languages/brazilian_portuguese.lua
  CorsixTH/Lua/languages/danish.lua
  CorsixTH/Lua/languages/english.lua
  CorsixTH/Lua/languages/finnish.lua
  CorsixTH/Lua/languages/hungarian.lua
  CorsixTH/Lua/languages/iberic_portuguese.lua
  CorsixTH/Lua/languages/italian.lua
  CorsixTH/Lua/languages/polish.lua
  CorsixTH/Lua/languages/russian.lua
  CorsixTH/Lua/languages/simplified_chinese.lua
  CorsixTH/Lua/languages/spanish.lua
  CorsixTH/Lua/languages/traditional_chinese.lua
Labels: PR:Translation

#2457 Show level briefing before the tutorial instead of after
  CorsixTH/Lua/game_ui.lua
  CorsixTH/Lua/world.lua
Labels: PR:Improvement

#2400 [RFC] Fix array indexing out of bounds in parcel adjacency calculation
  CorsixTH/Src/th_map.cpp
Labels: PR:Bugfix

#2481 Add semantic version comparison for updates
  CorsixTH/Lua/app.lua
Labels: PR:Bugfix, PR:Repo

#2468 Resize UIInformation
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/dialogs/information.lua
Labels: PR:Improvement

#2487 Disable audio in movies when there are no channels
  CorsixTH/Src/th_movie.cpp
  CorsixTH/Src/th_movie.h
Labels: PR:Bugfix

#2499 Fix some problems with mouse panning
  CorsixTH/Lua/game_ui.lua
Labels: PR:Bugfix

#2493 Vcpkg manifest
  .github/workflows/Linux.yml
  .github/workflows/Windows.yml
  .gitignore
  CMake/CopyVcpkgLua.cmake
  CMake/VcpkgDeps.cmake
  CMakeLists.txt
  CMakePresets.json
  CorsixTH/CMakeLists.txt
  appveyor.yml
  scripts/build_vcpkg_deps.ps1
  vcpkg-configuration.json
  vcpkg.json
Labels: PR:Build/Repo

#2492 Spawn a patient on open
  CorsixTH/Lua/dialogs/watch.lua
  CorsixTH/Lua/hospital.lua
  CorsixTH/Lua/hospitals/player_hospital.lua
Labels: PR:Improvement

#2489 Fix shutdown order
  CorsixTH/Src/sdl_core.cpp
  CorsixTH/SrcUnshared/main.cpp
Labels: PR:Bugfix

#2502 Add a link to the Snap in the install instructions in the README
  README.md
Labels: PR:Build/Repo
