Repository CorsixTH/CorsixTH, pull requests merged in 2024-09, with the labels that each got.

#2595 Add next version experiments
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: PR:Build/Repo

#2597 Fix long windows
  CorsixTH/Lua/dialogs/edit_room.lua
  CorsixTH/Lua/walls/external.lua
Labels: PR:Bugfix

#2607 Update Brazilian Portuguese Translation
  CorsixTH/Lua/languages/brazilian_portuguese.lua
  LICENSE.txt
Labels: PR:Translation

#2610 Prep for next prerelease
  CorsixTH/Lua/app.lua
  CorsixTH/com.corsixth.corsixth.metainfo.xml
  CorsixTH/corsix-th.6
  LICENSE.txt
  WindowsInstaller/Win32Script.nsi
  changelog.txt
Labels: PR:Build/Repo

#2618 Safeguard cheat transfer
  CorsixTH/Lua/hospitals/player_hospital.lua
Labels: PR:Bugfix

#2620 Fix copy/paste bugs in dutch research screen inc/dec tooltips.
  CorsixTH/Lua/languages/dutch.lua
Labels: PR:Translation

#2538 Don't clear patient_wait mood on seek_room interrupt
  CorsixTH/Lua/humanoid_actions/seek_room.lua
Labels: PR:Bugfix

#2621 Updated ukrainian language
  CorsixTH/Lua/languages/ukrainian.lua
Labels: PR:Translation

#2635 Russian language improvements
  CorsixTH/Lua/languages/russian.lua
Labels: PR:Translation

#2626 Update for 0.68.0 RC2
  CorsixTH/Lua/app.lua
  CorsixTH/com.corsixth.corsixth.metainfo.xml
  CorsixTH/corsix-th.6
  WindowsInstaller/Win32Script.nsi
  changelog.txt
Labels: PR:Build/Repo
