Repository CorsixTH/CorsixTH, pull requests merged in 2024-05, with the labels that each got.

#2560 Switch to libcurl for update check
  .github/workflows/Linux.yml
  CMake/CopyVcpkgLua.cmake
  CMakeLists.txt
  CMakePresets.json
  CorsixTH/CMakeLists.txt
  CorsixTH/Lua/api_version.lua
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/dialogs/resizables/main_menu.lua
  CorsixTH/Lua/dialogs/resizables/options.lua
  CorsixTH/Src/config.h.in
  CorsixTH/Src/th_lua.cpp
  CorsixTH/SrcUnshared/main.cpp
  LICENSE.txt
  scripts/macos_luarocks
  vcpkg.json
Labels: PR:Improvement, PR:Build/Repo

#2566 Use tired values from level config for staff tiredness
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/base_config.lua
  CorsixTH/Lua/entities/humanoids/staff.lua
  CorsixTH/Lua/entities/humanoids/staff/doctor.lua
  CorsixTH/Lua/entities/humanoids/vip.lua
  CorsixTH/Lua/hospital.lua
  CorsixTH/Lua/map.lua
Labels: PR:Improvement

#2559 Update italian translation
  CorsixTH/Lua/languages/italian.lua
Labels: PR:Translation

#2542 Add foundation code for using window active status
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/game_ui.lua
  CorsixTH/Lua/ui.lua
Labels: PR:Feature

#2552 Add descriptive audio error messages
  CorsixTH/Lua/audio.lua
  CorsixTH/Lua/languages/english.lua
Labels: PR:Improvement

#2484 Add groups to win/lose criteria
  .luacheckrc
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/dialogs/fullscreen/progress_report.lua
  CorsixTH/Lua/endconditions.lua
  CorsixTH/Lua/world.lua
Labels: PR:Improvement, PR:Refactor
