Repository CorsixTH/CorsixTH, pull requests merged in 2024-12, with the labels that each got.

#2733 Fix spawn contagious patient cheat
  CorsixTH/Lua/hospital.lua
Labels: PR:Bugfix

#2728 Count long windows as window of room
  CorsixTH/Lua/room.lua
Labels: PR:Bugfix

#2739 Use local time in gamelog filenames
  CorsixTH/Lua/app.lua
Labels: PR:Bugfix

#2745 Compute proper intensity of the text sprite pixels for constructing a TTF text colour.
  CorsixTH/Src/th_gfx_sdl.cpp
Labels: PR:Bugfix

#2737 Only capture mouse in game/mapeditor
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/dialogs/resizables/options.lua
  CorsixTH/Lua/game_ui.lua
  CorsixTH/Lua/languages/english.lua
Labels: PR:Improvement

#2746 Cleanup door-handling in walk action
  CorsixTH/Lua/humanoid_actions/walk.lua
Labels: PR:Refactor

#2740 #2738 stop epidemic timer on epidemic successfully eradicated
  CorsixTH/Lua/epidemic.lua
Labels: PR:Improvement

#2677 #2627 fix: 'free_build_mode' param affecting campaign maps.
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/dialogs/fullscreen/fax.lua
  CorsixTH/Lua/dialogs/menu.lua
  CorsixTH/Lua/dialogs/resizables/file_browsers/load_map.lua
  CorsixTH/Lua/dialogs/resizables/menu_list_dialogs/custom_game.lua
  CorsixTH/Lua/dialogs/resizables/new_game.lua
  CorsixTH/Lua/world.lua
Labels: PR:Bugfix
