Repository CorsixTH/CorsixTH, pull requests merged in 2024-03, with the labels that each got.

#2506 Linux dev preset for cmake
  CMakePresets.json
Labels: PR:Build/Repo

#2494 Adjust game speed and ticks
  CorsixTH/Lua/api_version.lua
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/world.lua
  CorsixTH/Src/lua_sdl.h
Labels: PR:Improvement

#2508 Add debug to linux-dev
  CMakePresets.json
Labels: PR:Build/Repo

#2497 Choose Closest Spawn for First Patient
  CorsixTH/Lua/hospital.lua
  CorsixTH/Lua/world.lua
Labels: PR:Improvement

#2391 Permit brackets in config values
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/utility.lua
Labels: PR:Bugfix

#1997 Add cheats to ingame menu
  CorsixTH/Lua/cheats.lua
  CorsixTH/Lua/dialogs/resizables/cheats_dialog.lua
  CorsixTH/Lua/hospital.lua
  CorsixTH/Lua/hospitals/player_hospital.lua
  CorsixTH/Lua/languages/english.lua
Labels: PR:Feature

#2517 Transfer active cheats on refresh
  CorsixTH/Lua/hospitals/player_hospital.lua
Labels: PR:Bugfix

#2513 Protected Call all Level Loads
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/dialogs/fullscreen/fax.lua
  CorsixTH/Lua/dialogs/menu.lua
  CorsixTH/Lua/dialogs/resizables/file_browsers/load_map.lua
  CorsixTH/Lua/dialogs/resizables/menu_list_dialogs/custom_game.lua
  CorsixTH/Lua/dialogs/resizables/new_game.lua
  CorsixTH/Lua/game_ui.lua
  CorsixTH/Lua/languages/english.lua
Labels: PR:Bugfix

#2206 Map editor menu improvement and refactoring
  CorsixTH/Lua/dialogs/menu.lua
Labels: PR:Feature

#2337 Rewrite empty if branches
  CorsixTH/Lua/humanoid_actions/use_object.lua
  CorsixTH/Lua/map.lua
Labels: PR:Refactor

#2491 Add Animview, 32bit, pr checkout on demand to Windows Actions
  .github/workflows/Windows.yml
Labels: PR:Build/Repo

#2535 Add Computer & Atom Analyser Entity Sounds
  CorsixTH/Src/th_gfx.cpp
Labels: PR:Bugfix

#2510 Dynamically Pair Swing Doors
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/objects/doors/swing_door_right.lua
Labels: PR:Bugfix

#2539 Add localised text to level and campaign descriptions and winning text
  CorsixTH/Campaigns/example.campaign
  CorsixTH/Levels/example.level
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/dialogs/resizables/menu_list_dialogs/custom_campaign.lua
  CorsixTH/Lua/languages/korean.lua
  CorsixTH/Lua/strings.lua
Labels: PR:Improvement
