Repository CorsixTH/CorsixTH, pull requests merged in 2024-10, with the labels that each got.

#2668 Allocate hotfix savegame versions
  CorsixTH/Lua/app.lua
Labels: PR:Build/Repo

#2654 Change gamelog render to yaml in issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: PR:Build/Repo

#2648 Reduce machine strength chance on repair tuned to match TH
  CorsixTH/Lua/entities/machine.lua
Labels: PR:Improvement

#2641 improved save_to_tmp string
  CorsixTH/Lua/languages/english.lua
Labels: PR:Improvement

#2629 Generalize whitespace check to catch TABs in source files
  .github/workflows/Linux.yml
  CorsixTH/Lua/languages/russian.lua
  CorsixTH/Lua/languages/ukrainian.lua
  scripts/check_trailing_whitespaces.py
  scripts/check_whitespace.py
Labels: PR:Build/Repo

#2634 Fix stuff not being able to be picked up while falling actions is active
  CorsixTH/Lua/entities/humanoids/patient.lua
Labels: PR:Bugfix

#2673 Updated change save_to_temp translation for the dutch language
  CorsixTH/Lua/languages/dutch.lua
Labels: PR:Translation

#2640 Improved tooltips in research screen
  CorsixTH/Lua/languages/english.lua
Labels: PR:Translation

#2637 updated VIP names in language files
  CorsixTH/Lua/languages/norwegian.lua
  CorsixTH/Lua/languages/polish.lua
  CorsixTH/Lua/languages/russian.lua
  CorsixTH/Lua/languages/simplified_chinese.lua
  CorsixTH/Lua/languages/traditional_chinese.lua
Labels: PR:Translation

#2616 Free build improvements in town map
  CorsixTH/Lua/dialogs/fullscreen/town_map.lua
Labels: PR:Improvement

#2686 Rename canPeePukeOrFall
  CorsixTH/Lua/entities/humanoids/patient.lua
Labels: PR:Refactor

#2666 Prevent staff grab spamming
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/dialogs/staff_dialog.lua
  CorsixTH/Lua/entities/humanoids/staff.lua
Labels: PR:Bugfix

#2652 Freeze patient's treatment cost when agreeing to pay
  CorsixTH/Lua/entities/humanoids/patient.lua
  CorsixTH/Lua/hospital.lua
Labels: PR:Improvement

#2578 End condtions and progress report dialog improvements
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/dialogs/fullscreen/progress_report.lua
  CorsixTH/Lua/endconditions.lua
Labels: PR:Improvement

#2691 Move idle ticks to follow app ticks
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/dialogs/resizables/main_menu.lua
Labels: PR:Bugfix

#2674 #2625 Fix: Auto satisfying salary request don't close window
  CorsixTH/Lua/dialogs/fullscreen/staff_management.lua
  CorsixTH/Lua/dialogs/staff_rise.lua
  CorsixTH/Lua/entities/humanoids/staff.lua
  CorsixTH/Lua/staff_profile.lua
Labels: PR:Bugfix

#2676 Improvements for ChrizmanTV Campaign Levels
  CorsixTH/Campaigns/Upper Pukington.map
  CorsixTH/Campaigns/dethsdaw.level
  CorsixTH/Campaigns/fourcorners.level
  CorsixTH/Campaigns/hoppalong.level
  CorsixTH/Campaigns/snuffitsands.level
  CorsixTH/Campaigns/upperpukington.level
  CorsixTH/Campaigns/wishinwell.level
Labels: PR:Bugfix
