Repository CorsixTH/CorsixTH, pull requests merged in 2024-08, with the labels that each got.

#1848 Changes supporting falling actions
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/config_finder.lua
  CorsixTH/Lua/dialogs/menu.lua
  CorsixTH/Lua/earthquake.lua
  CorsixTH/Lua/entities/humanoid.lua
  CorsixTH/Lua/entities/humanoids/patient.lua
  CorsixTH/Lua/humanoid_actions/falling.lua
  CorsixTH/Lua/humanoid_actions/get_up.lua
  CorsixTH/Lua/humanoid_actions/on_ground.lua
  CorsixTH/Lua/languages/english.lua
  WindowsInstaller/config_template.txt
Labels: PR:Improvement

#2584 Add Load/save buttons & save warning message
  CorsixTH/Lua/dialogs/resizables/file_browser.lua
  CorsixTH/Lua/dialogs/resizables/file_browsers/load_game.lua
  CorsixTH/Lua/dialogs/resizables/file_browsers/load_map.lua
  CorsixTH/Lua/dialogs/resizables/file_browsers/save_game.lua
  CorsixTH/Lua/dialogs/resizables/file_browsers/save_map.lua
  CorsixTH/Lua/languages/english.lua
Labels: PR:Improvement

#2588 Mark Right Mouse Scrolling Experimental
  CorsixTH/Lua/config_finder.lua
  CorsixTH/Lua/dialogs/resizables/options.lua
  CorsixTH/Lua/game_ui.lua
  WindowsInstaller/config_template.txt
Labels: PR:Improvement

#2593 Use new strings for load map window
  CorsixTH/Lua/dialogs/resizables/file_browsers/load_map.lua
  CorsixTH/Lua/languages/english.lua
  CorsixTH/Lua/languages/russian.lua
Labels: PR:Improvement

#2596 Copyrights 2024
  LICENSE.txt
Labels: PR:Build/Repo

#2572 Add Actions for Windows Installer
  .github/workflows/Windows.yml
  .github/workflows/WindowsInstaller.yml
  CorsixTH/CMakeLists.txt
  WindowsInstaller/Win32Script.nsi
Labels: PR:Build/Repo

#2598 Temporarily Bump Very Old Save
  CorsixTH/Lua/world.lua
Labels: PR:Build/Repo

#2591 updated Italian translation, correct spelling
  CorsixTH/Lua/languages/italian.lua
Labels: PR:Translation

#2601 Changelog 0.68.0
  changelog.txt
Labels: PR:Build/Repo
