Repository CorsixTH/CorsixTH, pull requests merged in 2025-09, with the labels that each got.

#2992 Regressed crash on cancel grab after room exploded fix
  CorsixTH/Lua/dialogs/place_staff.lua
Labels: PR:Bugfix

#2993 Improve finding player name
  CorsixTH/Lua/app.lua
Labels: PR:Improvement

#2977 Late diagnosis termination bug fix.
  CorsixTH/Lua/entities/humanoids/patient.lua
  CorsixTH/Lua/rooms/gp.lua
Labels: PR:Bugfix

#3009 Improved tooltips in Build Rooms/Furnish Corridor menus
  CorsixTH/Lua/languages/english.lua
Labels: PR:Translation

#3012 Fix regular expressions in readLevelInfo
  CorsixTH/Lua/app.lua
Labels: PR:Bugfix

#2915 Remember active graphs
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/dialogs/fullscreen/graphs.lua
Labels: PR:Feature

#3019 Update french.lua -- Add French translations for the machine menu
  CorsixTH/Lua/languages/french.lua
Labels: PR:Translation

#2968 Let staff return to training/research
  CorsixTH/Lua/entities/humanoids/staff.lua
  CorsixTH/Lua/entities/humanoids/staff/doctor.lua
  CorsixTH/Lua/rooms/training.lua
Labels: PR:Bugfix

#3026 render_target RAII
  CorsixTH/Lua/api_version.lua
  CorsixTH/Src/th_gfx.h
  CorsixTH/Src/th_gfx_sdl.cpp
  CorsixTH/Src/th_gfx_sdl.h
  CorsixTH/Src/th_lua_gfx.cpp
Labels: PR:Refactor

#3033 Fix the tile coordinates of the animations at the east wall.
  CorsixTH/Src/th_lua_map.cpp
Labels: PR:Bugfix

#3023 Improvements to labels and tooltips in Custom Settings menu
  CorsixTH/Lua/dialogs/resizables/customise.lua
  CorsixTH/Lua/languages/english.lua
Labels: PR:Improvement

#3053 Drop WX stringimpl.h header include
  AnimView/frmMain.cpp
Labels: C:AnimView, bug
