Repository CorsixTH/CorsixTH, pull requests merged in 2025-08, with the labels that each got.

#2955 Fix font74v compat
  CorsixTH/Lua/dialogs/fullscreen/hospital_policy.lua
  CorsixTH/Lua/dialogs/patient.lua
Labels: PR:Bugfix, PR:Translation

#2962 Hotfix room crash on placing staff
  CorsixTH/Lua/entities/humanoids/staff.lua
Labels: PR:Bugfix

#2961 RFC: Cpp 17 and RAII refactor
  AnimView/CMakeLists.txt
  AnimView/frmMain.cpp
  AnimView/frmMain.h
  AnimView/th.cpp
  AnimView/th.h
  CorsixTH/CMakeLists.txt
  CorsixTH/CppTest/CMakeLists.txt
  CorsixTH/CppTest/test_th_lua_map.cpp
  CorsixTH/Lua/api_version.lua
  CorsixTH/Lua/dialogs/resizables/directory_browser.lua
  CorsixTH/Lua/filesystem.lua
  CorsixTH/Src/iso_fs.cpp
  CorsixTH/Src/iso_fs.h
  CorsixTH/Src/main.cpp
  CorsixTH/Src/persist_lua.cpp
  CorsixTH/Src/persist_lua.h
  CorsixTH/Src/run_length_encoder.cpp
  CorsixTH/Src/run_length_encoder.h
  CorsixTH/Src/sdl_audio.cpp
  CorsixTH/Src/sdl_core.cpp
  CorsixTH/Src/th.cpp
  CorsixTH/Src/th.h
  CorsixTH/Src/th_gfx.cpp
  CorsixTH/Src/th_gfx.h
  CorsixTH/Src/th_gfx_font.cpp
  CorsixTH/Src/th_gfx_font.h
  CorsixTH/Src/th_gfx_sdl.cpp
  CorsixTH/Src/th_gfx_sdl.h
  CorsixTH/Src/th_lua.h
  CorsixTH/Src/th_lua_anims.cpp
  CorsixTH/Src/th_lua_gfx.cpp
  CorsixTH/Src/th_lua_iso.cpp
  CorsixTH/Src/th_lua_map.cpp
  CorsixTH/Src/th_map.cpp
  CorsixTH/Src/th_map.h
  CorsixTH/Src/th_map_overlays.cpp
  CorsixTH/Src/th_map_overlays.h
  CorsixTH/Src/th_movie.cpp
  CorsixTH/Src/th_movie.h
  CorsixTH/Src/th_pathfind.cpp
  CorsixTH/Src/th_pathfind.h
  CorsixTH/Src/th_sound.cpp
  CorsixTH/SrcUnshared/main.cpp
  tools/rnc/CMakeLists.txt
Labels: PR:Build/Repo

#2958 Add drawing layers constants
  .luacheckrc
  CorsixTH/Lua/entities/humanoid.lua
  CorsixTH/Lua/entities/humanoids/staff.lua
  CorsixTH/Lua/entities/humanoids/staff/receptionist.lua
  CorsixTH/Lua/entities/object.lua
  CorsixTH/Lua/entity.lua
  CorsixTH/Lua/objects/analyser.lua
  CorsixTH/Lua/objects/bin.lua
  CorsixTH/Lua/objects/door.lua
  CorsixTH/Lua/objects/litter.lua
  CorsixTH/Lua/objects/rathole.lua
  CorsixTH/Lua/utility.lua
  CorsixTH/Luatest/spec/entities/machine_spec.lua
  CorsixTH/Luatest/spec/entities/object_spec.lua
Labels: PR:Improvement

#2972 Update screenshot function
  CorsixTH/Lua/ui.lua
Labels: PR:Improvement

#2953 Always crop at tile edges.
  CorsixTH/Src/th_gfx.cpp
Labels: PR:Build/Repo

#2969 Eliminate pragma pack casts and raw memory in sound
  CorsixTH/Src/th_sound.cpp
  CorsixTH/Src/th_sound.h
Labels: PR:Build/Repo

#2979 Better error handling for non-existent languages
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/strings.lua
Labels: PR:Improvement, PR:Bugfix

#2966 Toolbar machine button
  CorsixTH/Bitmap/aux_ui.dat
  CorsixTH/Bitmap/aux_ui.spec
  CorsixTH/Bitmap/aux_ui.tab
  CorsixTH/Bitmap/machinemenu.bmp
  CorsixTH/Bitmap/machinemenupressed.bmp
  CorsixTH/Bitmap/toolbar_machinemenu_idle.bmp
  CorsixTH/Bitmap/toolbar_machinemenu_pressed.bmp
  CorsixTH/Lua/config_finder.lua
  CorsixTH/Lua/dialogs/bottom_panel.lua
  CorsixTH/Lua/dialogs/machine_dialog.lua
  CorsixTH/Lua/dialogs/resizables/customise.lua
  CorsixTH/Lua/languages/english.lua
  CorsixTH/Lua/languages/french.lua
  CorsixTH/Lua/languages/german.lua
  CorsixTH/Lua/languages/russian.lua
  CorsixTH/Lua/languages/spanish.lua
  WindowsInstaller/config_template.txt
Labels: PR:Feature

#2957 Include machine and cost parameters for replacement dialog
  CorsixTH/Lua/languages/french.lua
Labels: PR:Translation

#2980 Remove target memory layout assumptions from CorsixTH resource loading
  CorsixTH/Src/bootstrap.cpp
  CorsixTH/Src/persist_lua.cpp
  CorsixTH/Src/th.cpp
  CorsixTH/Src/th_gfx.cpp
  CorsixTH/Src/th_gfx.h
  CorsixTH/Src/th_gfx_sdl.cpp
  CorsixTH/Src/th_gfx_sdl.h
  CorsixTH/Src/th_lua_map.cpp
  changelog.txt
Labels: PR:Refactor, PR:Build/Repo

#2973 Reworked Czech translation
  CorsixTH/Lua/languages/czech.lua
Labels: PR:Translation

#2985 Minor cleanup load_multi_buffer
  CorsixTH/Src/persist_lua.cpp
Labels: PR:Refactor

#2987 Store the tile position of an animation in the animation.
  CorsixTH/Src/th_gfx.cpp
  CorsixTH/Src/th_gfx.h
  CorsixTH/Src/th_lua_anims.cpp
  CorsixTH/Src/th_lua_map.cpp
Labels: PR:Improvement
