Repository CorsixTH/CorsixTH, pull requests merged in 2025-07, with the labels that each got.

#2928 Download Noto font and include in Windows installer
  .github/workflows/WindowsInstaller.yml
Labels: PR:Build/Repo

#2934 Refresh 0.69.0 rc1 changelog
  CorsixTH/com.corsixth.corsixth.metainfo.xml
  LICENSE.txt
  changelog.txt
Labels: PR:Build/Repo

#2940 Prep for 0.69 release
  CorsixTH/Lua/app.lua
  CorsixTH/com.corsixth.corsixth.metainfo.xml
  CorsixTH/corsix-th.6
  WindowsInstaller/Win32Script.nsi
  changelog.txt
Labels: PR:Build/Repo

#2942 Savegame bump post-release
  CorsixTH/Lua/app.lua
Labels: PR:Build/Repo

#2935 Refactor rendering
  CorsixTH/Src/th_map.cpp
  CorsixTH/Src/th_map.h
Labels: C:SDL2, PR:Refactor

#2910 Add machine menu button to machine dialog
  CorsixTH/Bitmap/aux_ui.dat
  CorsixTH/Bitmap/aux_ui.spec
  CorsixTH/Bitmap/aux_ui.tab
  CorsixTH/Bitmap/machinemenu.bmp
  CorsixTH/Bitmap/machinemenupressed.bmp
  CorsixTH/Lua/dialogs/machine_dialog.lua
  CorsixTH/Lua/languages/english.lua
  CorsixTH/Lua/languages/french.lua
  CorsixTH/Lua/languages/german.lua
  CorsixTH/Lua/languages/russian.lua
  CorsixTH/Lua/languages/spanish.lua
Labels: PR:Feature
