Repository CorsixTH/CorsixTH, pull requests merged in 2025-04, with the labels that each got.

#2810 On pickup surgeon remove surgical gown
  CorsixTH/Lua/entities/humanoids/staff.lua
  CorsixTH/Lua/entities/humanoids/staff/doctor.lua
  CorsixTH/Lua/humanoid_actions/pickup.lua
Labels: PR:Bugfix

#2089 Set volume straight after music is set playing
  CorsixTH/Lua/audio.lua
Labels: PR:Bugfix

#2815 Afteload minor fix in world.lua
  CorsixTH/Lua/world.lua
Labels: PR:Build/Repo

#2813 Add support for AddressSanitizer, drop VLD
  CMakeLists.txt
  CMakePresets.json
  CorsixTH/CMakeLists.txt
Labels: PR:Build/Repo

#2808 Refactor drawable draw / hit_test / is_multiple_frame_animation methods
  CorsixTH/Src/th_gfx.cpp
  CorsixTH/Src/th_gfx.h
  CorsixTH/Src/th_lua.h
  CorsixTH/Src/th_map.cpp
Labels: PR:Refactor

#2817 Fix stuck wait moods
  CorsixTH/Lua/room.lua
Labels: PR:Bugfix

#2818 Allow using the secondary marker
  CorsixTH/Lua/api_version.lua
  CorsixTH/Src/th_gfx.cpp
  CorsixTH/Src/th_gfx.h
  CorsixTH/Src/th_lua_anims.cpp
Labels: PR:Feature

#2820 Remove obsolete getMarker/setFrameMarker
  CorsixTH/Lua/api_version.lua
  CorsixTH/Lua/dialogs/fullscreen/staff_management.lua
  CorsixTH/Lua/dialogs/patient.lua
  CorsixTH/Lua/dialogs/resizables/calls_dispatcher.lua
  CorsixTH/Lua/dialogs/staff_dialog.lua
  CorsixTH/Lua/dialogs/staff_rise.lua
  CorsixTH/Lua/graphics.lua
  CorsixTH/Src/th_lua_anims.cpp
Labels: PR:Refactor

#2814 Operation Theatre. Surgeons should not stuck
  CorsixTH/Lua/rooms/operating_theatre.lua
Labels: PR:Bugfix

#2825 Use lua_Integer instead of uint32_t to avoid a warning about possible loss of data
  CorsixTH/Src/th_lua_anims.cpp
Labels: PR:Build/Repo

#2793 Add machine menu
  .luacheckrc
  CorsixTH/Lua/config_finder.lua
  CorsixTH/Lua/dialogs/bottom_panel.lua
  CorsixTH/Lua/dialogs/menu.lua
  CorsixTH/Lua/dialogs/resizables/hotkey_assign.lua
  CorsixTH/Lua/dialogs/resizables/machine_menu.lua
  CorsixTH/Lua/languages/english.lua
  CorsixTH/Lua/languages/russian.lua
  CorsixTH/Lua/languages/spanish.lua
Labels: PR:Feature

#2823 Fix campaign restart 2
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/dialogs/fullscreen/fax.lua
  CorsixTH/Lua/languages/english.lua
  CorsixTH/Lua/world.lua
Labels: PR:Bugfix

#2398 Look for a bundled Noto CJK font
  CMakeLists.txt
  CorsixTH/CMakeLists.txt
  CorsixTH/Lua/api_version.lua
  CorsixTH/Lua/graphics.lua
  CorsixTH/Src/config.h.in
  CorsixTH/Src/th_lua.cpp
Labels: PR:Feature, PR:need-rebase

#2816 Queue minor refactoring
  CorsixTH/Lua/queue.lua
Labels: PR:Refactor

#2822 Operation Theatre. Remove resume surgery operation
  CorsixTH/Lua/rooms/operating_theatre.lua
Labels: PR:Bugfix

#2133 Change how staff find work
  CorsixTH/Lua/calls_dispatcher.lua
  CorsixTH/Lua/entities/humanoids/staff.lua
  CorsixTH/Lua/hospitals/player_hospital.lua
  CorsixTH/Lua/room.lua
  CorsixTH/Lua/rooms/gp.lua
Labels: PR:Improvement

#2833 Option for CMake to fetch Catch2
  CMakeLists.txt
  CorsixTH/CppTest/CMakeLists.txt
Labels: PR:Build/Repo

#2835 Fix animation refactor regression
  CorsixTH/Src/persist_lua.cpp
  CorsixTH/Src/th.h
  CorsixTH/Src/th_gfx.cpp
  CorsixTH/Src/th_gfx.h
  CorsixTH/Src/th_map.cpp
Labels: PR:Bugfix

#2812 Operation Theatre. Prevent pickup surgeon during surgery operation
  CorsixTH/Lua/entities/humanoid.lua
  CorsixTH/Lua/humanoid_action.lua
  CorsixTH/Lua/humanoid_actions/use_object.lua
  CorsixTH/Lua/rooms/operating_theatre.lua
Labels: PR:Bugfix
