Repository CorsixTH/CorsixTH, pull requests merged in 2025-03, with the labels that each got.

#2786 Adjust mood icons
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/entities/humanoid.lua
  CorsixTH/Lua/entities/humanoids/patient.lua
Labels: PR:Improvement, PR:Bugfix

#2783 Add method for sprite visibility test
  CorsixTH/Src/th_gfx_sdl.cpp
  CorsixTH/Src/th_gfx_sdl.h
  CorsixTH/Src/th_lua_gfx.cpp
Labels: PR:Improvement

#2752 Cleanup/"fix" the UseObjectAction
  CorsixTH/Lua/entities/machine.lua
  CorsixTH/Lua/humanoid_actions/use_object.lua
Labels: PR:Bugfix, PR:Refactor

#2197 Add Poisson distribution function.
  .luacheckrc
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/world.lua
Labels: PR:Feature

#2768 Remove Serious Radiation epidemics
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/hospital.lua
  CorsixTH/Lua/hospitals/player_hospital.lua
Labels: PR:Bugfix

#2789 Fix tick_rate remapping
  CorsixTH/Lua/world.lua
Labels: PR:Bugfix

#2756 Include the users campaign dir in looking for campaigns
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/dialogs/fullscreen/fax.lua
  CorsixTH/Lua/dialogs/resizables/menu_list_dialogs/custom_campaign.lua
  CorsixTH/Lua/dialogs/resizables/menu_list_dialogs/custom_game.lua
  CorsixTH/Lua/languages/english.lua
  CorsixTH/Lua/map.lua
  CorsixTH/Lua/world.lua
Labels: PR:Improvement, PR:Bugfix

#2781 Epidemic refactoring. `coverup_in_progress` rename.
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/dialogs/watch.lua
  CorsixTH/Lua/entities/humanoids/patient.lua
  CorsixTH/Lua/epidemic.lua
  CorsixTH/Lua/game_ui.lua
  CorsixTH/Lua/hospital.lua
  CorsixTH/Lua/humanoid_actions/vaccinate.lua
Labels: PR:Refactor

#2800 Bump vcpkg for 2025-03-21
  .github/workflows/Windows.yml
  vcpkg-configuration.json
Labels: PR:Build/Repo

#2802 Add interpeter path for portable linux installs
  CorsixTH/Src/main.cpp
Labels: PR:Build/Repo

#2803 Object/Machine updateDynamicInfo should not increase object usage
  CorsixTH/Lua/dialogs/place_objects.lua
  CorsixTH/Lua/earthquake.lua
  CorsixTH/Lua/entities/humanoids/vip.lua
  CorsixTH/Lua/entities/machine.lua
  CorsixTH/Lua/entities/object.lua
  CorsixTH/Lua/humanoid_actions/multi_use_object.lua
  CorsixTH/Lua/humanoid_actions/use_object.lua
  CorsixTH/Lua/research_department.lua
  CorsixTH/Luatest/spec/entities/humanoids/vip_spec.lua
  CorsixTH/Luatest/spec/entities/machine_spec.lua
Labels: PR:Refactor
