Repository CorsixTH/CorsixTH, pull requests merged in 2025-01, with the labels that each got.

#2754 Add soundfont setting to config
  CorsixTH/Lua/config_finder.lua
  WindowsInstaller/config_template.txt
Labels: PR:Improvement

#2757 Remove duplicate call to open the win fax
  CorsixTH/Lua/dialogs/fullscreen/annual_report.lua
Labels: PR:Bugfix

#2755 Fix advice when exceeding maximum buy object limit
  CorsixTH/Lua/dialogs/furnish_corridor.lua
  CorsixTH/Lua/languages/brazilian_portuguese.lua
  CorsixTH/Lua/languages/english.lua
Labels: PR:Improvement

#2763 Instant speed changes
  CorsixTH/Lua/world.lua
Labels: PR:Improvement

#2753 Fix for: Deactivate epidemics cheat doesn't work.
  CorsixTH/Lua/cheats.lua
  CorsixTH/Lua/dialogs/bottom_panel.lua
  CorsixTH/Lua/dialogs/fullscreen/fax.lua
  CorsixTH/Lua/epidemic.lua
  CorsixTH/Lua/hospital.lua
  CorsixTH/Lua/languages/english.lua
Labels: PR:Improvement

#2615 Allow switching between staff by using staff name label
  CorsixTH/Lua/dialogs/staff_dialog.lua
Labels: PR:Feature

#2767 Improve cheat feedback
  CorsixTH/Lua/dialogs/resizables/cheats_dialog.lua
  CorsixTH/Lua/hospital.lua
  CorsixTH/Lua/languages/english.lua
  CorsixTH/Lua/languages/french.lua
  CorsixTH/Lua/languages/russian.lua
  CorsixTH/Lua/languages/spanish.lua
  LICENSE.txt
Labels: PR:Bugfix, PR:Translation
