Repository CorsixTH/CorsixTH, pull requests merged in 2025-10, with the labels that each got.

#3052 Epidemic. Vaccination cursor does not work fix
  CorsixTH/Lua/entities/humanoids/patient.lua
Labels: PR:Bugfix

#3030 Add missing hover and click sound effects in various places
  CorsixTH/Lua/dialogs/build_room.lua
  CorsixTH/Lua/dialogs/fullscreen/hospital_policy.lua
  CorsixTH/Lua/dialogs/fullscreen/staff_management.lua
  CorsixTH/Lua/dialogs/furnish_corridor.lua
  CorsixTH/Lua/dialogs/information.lua
  CorsixTH/Lua/dialogs/menu.lua
  CorsixTH/Lua/dialogs/patient.lua
  CorsixTH/Lua/dialogs/place_objects.lua
  CorsixTH/Lua/dialogs/staff_dialog.lua
  CorsixTH/Lua/dialogs/watch.lua
  CorsixTH/Lua/game_ui.lua
  CorsixTH/Lua/window.lua
Labels: PR:Feature

#3059 Shrink the right margin of the fax
  CorsixTH/Lua/dialogs/fullscreen/fax.lua
Labels: PR:Bugfix

#3060 Fix smoke machine position
  CorsixTH/Lua/entities/machine.lua
  CorsixTH/Lua/entities/object.lua
  CorsixTH/Lua/objects/machines/blood_machine.lua
  CorsixTH/Lua/objects/machines/cardio.lua
  CorsixTH/Lua/objects/machines/cast_remover.lua
  CorsixTH/Lua/objects/machines/dna_fixer.lua
  CorsixTH/Lua/objects/machines/electrolyser.lua
  CorsixTH/Lua/objects/machines/hair_restorer.lua
  CorsixTH/Lua/objects/machines/inflator.lua
  CorsixTH/Lua/objects/machines/jelly_moulder.lua
  CorsixTH/Lua/objects/machines/operating_table.lua
  CorsixTH/Lua/objects/machines/scanner.lua
  CorsixTH/Lua/objects/machines/shower.lua
  CorsixTH/Lua/objects/machines/slicer.lua
  CorsixTH/Lua/objects/machines/ultrascanner.lua
  CorsixTH/Lua/objects/machines/x_ray.lua
Labels: PR:Improvement
