Repository CorsixTH/CorsixTH, pull requests merged in 2025-06, with the labels that each got.

#2893 Fix map editor load and save
  CorsixTH/Lua/dialogs/resizables/file_browsers/load_map.lua
  CorsixTH/Lua/world.lua
Labels: PR:Bugfix

#2894 Load correct level end praise
  CorsixTH/Lua/world.lua
Labels: PR:Bugfix

#2891 0.69.0 Beta 1 changelog
  CorsixTH/com.corsixth.corsixth.metainfo.xml
  changelog.txt
Labels: PR:Build/Repo

#2898 Handle in-flight actions without mood marker
  CorsixTH/Lua/entity.lua
Labels: PR:Bugfix

#2904 Fix misnamed function call loading font for hotkeys
  CorsixTH/Lua/graphics.lua
Labels: PR:Bugfix

#2892 Allow one or two sounds to be played with an animation frame
  CorsixTH/Src/th_gfx.cpp
Labels: PR:Improvement

#2919 Restore handyman cleaning abilities
  CorsixTH/Lua/hospitals/player_hospital.lua
Labels: PR:Bugfix

#2923 Add missed contributor
  LICENSE.txt
Labels: PR:Build/Repo

#2922 0.69.0 Beta 2 changelog
  CorsixTH/com.corsixth.corsixth.metainfo.xml
  changelog.txt
Labels: PR:Build/Repo

#2518 Encourage level restarts on very_old_saves
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/dialogs/resizables/main_menu.lua
  CorsixTH/Lua/languages/czech.lua
  CorsixTH/Lua/languages/dutch.lua
  CorsixTH/Lua/languages/english.lua
  CorsixTH/Lua/languages/french.lua
  CorsixTH/Lua/languages/spanish.lua
  CorsixTH/Lua/world.lua
Labels: PR:Feature, PR:Build/Repo
