Repository CorsixTH/CorsixTH, pull requests merged in 2025-05, with the labels that each got.

#2841 Afterload minor fix in earthquake.lua
  CorsixTH/Lua/earthquake.lua
Labels: PR:Build/Repo

#2824 Marker split add and improve
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/dialogs/fullscreen/staff_management.lua
  CorsixTH/Lua/dialogs/place_staff.lua
  CorsixTH/Lua/dialogs/resizables/calls_dispatcher.lua
  CorsixTH/Lua/dialogs/resizables/menu_list_dialogs/make_debug_patient.lua
  CorsixTH/Lua/dialogs/staff_dialog.lua
  CorsixTH/Lua/dialogs/staff_rise.lua
  CorsixTH/Lua/entities/humanoid.lua
  CorsixTH/Lua/entities/humanoids/grim_reaper.lua
  CorsixTH/Lua/entities/humanoids/inspector.lua
  CorsixTH/Lua/entities/humanoids/patient.lua
  CorsixTH/Lua/entities/humanoids/staff.lua
  CorsixTH/Lua/entities/humanoids/vip.lua
  CorsixTH/Lua/entities/machine.lua
  CorsixTH/Lua/entity.lua
  CorsixTH/Lua/epidemic.lua
  CorsixTH/Lua/graphics.lua
  CorsixTH/Lua/hospital.lua
  CorsixTH/Lua/humanoid_actions/die.lua
  CorsixTH/Lua/humanoid_actions/sweep_floor.lua
  CorsixTH/Lua/humanoid_actions/use_screen.lua
  CorsixTH/Lua/objects/autopsy.lua
  CorsixTH/Lua/objects/bed.lua
  CorsixTH/Lua/objects/cabinet.lua
  CorsixTH/Lua/objects/desk.lua
  CorsixTH/Lua/objects/gates_to_hell.lua
  CorsixTH/Lua/objects/helicopter.lua
  CorsixTH/Lua/objects/lecture_chair.lua
  CorsixTH/Lua/objects/loo.lua
  CorsixTH/Lua/objects/machines/blood_machine.lua
  CorsixTH/Lua/objects/machines/cardio.lua
  CorsixTH/Lua/objects/machines/cast_remover.lua
  CorsixTH/Lua/objects/machines/electrolyser.lua
  CorsixTH/Lua/objects/machines/hair_restorer.lua
  CorsixTH/Lua/objects/machines/inflator.lua
  CorsixTH/Lua/objects/machines/operating_table.lua
  CorsixTH/Lua/objects/machines/scanner.lua
  CorsixTH/Lua/objects/machines/slicer.lua
  CorsixTH/Lua/objects/machines/ultrascanner.lua
  CorsixTH/Lua/objects/machines/x_ray.lua
  CorsixTH/Lua/objects/plant.lua
  CorsixTH/Lua/objects/projector.lua
  CorsixTH/Lua/objects/sink.lua
  CorsixTH/Lua/objects/sofa.lua
  CorsixTH/Lua/world.lua
  CorsixTH/Luatest/TH.lua
Labels: PR:Improvement, PR:Bugfix

#2845 Fix cabinet staff marker
  CorsixTH/Lua/objects/cabinet.lua
Labels: PR:Bugfix

#2846 Clean up obsolete cmake options
  .github/workflows/Linux.yml
  CMake/FindVLD.cmake
  CMake/PrecompiledDeps.cmake
  CMakeLists.txt
  CorsixTH/Src/config.h.in
  CorsixTH/Src/main.h
Labels: PR:Build/Repo

#2839 Fix pick up surgeon skips hand washing
  CorsixTH/Lua/rooms/operating_theatre.lua
Labels: PR:Bugfix

#2851 Fix markers in toilets
  CorsixTH/Lua/objects/loo.lua
  CorsixTH/Lua/objects/sink.lua
Labels: PR:Bugfix

#2849 Fix Linear Interpolation for markers
  CorsixTH/Lua/graphics.lua
Labels: PR:Bugfix

#2847 Eliminate world.animation_manager
  CorsixTH/Lua/app.lua
  CorsixTH/Lua/hospitals/player_hospital.lua
  CorsixTH/Lua/humanoid_actions/check_watch.lua
  CorsixTH/Lua/humanoid_actions/die.lua
  CorsixTH/Lua/humanoid_actions/falling.lua
  CorsixTH/Lua/humanoid_actions/get_up.lua
  CorsixTH/Lua/humanoid_actions/idle_spawn.lua
  CorsixTH/Lua/humanoid_actions/knock_door.lua
  CorsixTH/Lua/humanoid_actions/multi_use_object.lua
  CorsixTH/Lua/humanoid_actions/on_ground.lua
  CorsixTH/Lua/humanoid_actions/pee.lua
  CorsixTH/Lua/humanoid_actions/shake_fist.lua
  CorsixTH/Lua/humanoid_actions/sweep_floor.lua
  CorsixTH/Lua/humanoid_actions/tap_foot.lua
  CorsixTH/Lua/humanoid_actions/use_object.lua
  CorsixTH/Lua/humanoid_actions/use_screen.lua
  CorsixTH/Lua/humanoid_actions/vomit.lua
  CorsixTH/Lua/humanoid_actions/walk.lua
  CorsixTH/Lua/humanoid_actions/yawn.lua
  CorsixTH/Lua/objects/doors/swing_door_right.lua
  CorsixTH/Lua/world.lua
Labels: PR:Refactor

#2850 Extend animview
  AnimView/frmMain.cpp
  AnimView/frmMain.h
Labels: C:AnimView, PR:Feature, PR:Build/Repo

#2844 General Diagnosis. Crash fixes on doctor change
  CorsixTH/Lua/entities/humanoid.lua
  CorsixTH/Lua/entities/humanoids/staff.lua
  CorsixTH/Lua/room.lua
  CorsixTH/Lua/rooms/general_diag.lua
Labels: PR:Bugfix

#2860 Fix swingdoor mood
  CorsixTH/Lua/entities/humanoid.lua
Labels: PR:Bugfix

#2868 Replace clang::suppress attribute
  CorsixTH/Src/th_gfx_sdl.cpp
Labels: PR:Build/Repo

#2869 Fix moods of the comfortable chair.
  CorsixTH/Lua/objects/comfortable_chair.lua
Labels: PR:Bugfix

#2858 Staff Management. Press on staff window interferes world.
  CorsixTH/Lua/dialogs/fullscreen/staff_management.lua
Labels: PR:Bugfix

#2856 Fix operating theatre and screen markers
  CorsixTH/Lua/humanoid_actions/use_screen.lua
  CorsixTH/Lua/objects/machines/operating_table.lua
  CorsixTH/Lua/objects/machines/operating_table_b.lua
  CorsixTH/Lua/objects/screen.lua
  CorsixTH/Lua/objects/surgeon_screen.lua
Labels: PR:Bugfix

#2843 Kill staff returned to crashed rooms
  CorsixTH/Lua/dialogs/place_staff.lua
  CorsixTH/Lua/humanoid_actions/pickup.lua
Labels: PR:Bugfix

#2877 Dont play drop sound on cancel hire
  CorsixTH/Lua/dialogs/place_staff.lua
Labels: PR:Bugfix

#2878 Fix Windows Actions caching
  .github/workflows/Windows.yml
Labels: PR:Build/Repo

#2880 Refactor th map cpp
  CorsixTH/Src/config.h.in
  CorsixTH/Src/th_lua_map.cpp
  CorsixTH/Src/th_lua_ui.cpp
  CorsixTH/Src/th_map.cpp
  CorsixTH/Src/th_map.h
Labels: PR:Refactor

#2883 Fix place staff regression
  CorsixTH/Lua/dialogs/place_staff.lua
Labels: PR:Bugfix
