Repository CorsixTH/CorsixTH, pull requests merged in 2025-02, with the labels that each got.

#2771 Replace calculateSpawnTiles repeat loop
  CorsixTH/Lua/world.lua
Labels: PR:Refactor

#2774 Russian translation improvements
  CorsixTH/Lua/languages/russian.lua
  CorsixTH/Lua/languages/ukrainian.lua
Labels: PR:Translation

#2761 Add adviser messages for patients waiting for a staffed gps office
  CorsixTH/Lua/hospital.lua
  CorsixTH/Lua/hospitals/player_hospital.lua
  CorsixTH/Lua/humanoid_actions/seek_room.lua
  CorsixTH/Lua/languages/english.lua
Labels: PR:Feature

#2748 Calculate Epidemic outcome on inspector arrive
  CorsixTH/Lua/epidemic.lua
  CorsixTH/Lua/objects/reception_desk.lua
Labels: PR:Improvement

#2762 Change reroute behaviour on trimmed paths
  CorsixTH/Lua/humanoid_actions/seek_reception.lua
  CorsixTH/Lua/humanoid_actions/walk.lua
Labels: PR:Bugfix

#2782 Fix typo in lightness calculation
  CorsixTH/Src/th_gfx_sdl.cpp
Labels: PR:Bugfix

#2785 Adjust random announcement target
  CorsixTH/Lua/announcer.lua
Labels: PR:Bugfix
